Repository ExpediaGroup/expediagroup-java-sdk, pull requests merged in 2022-10, with the labels that each got.

#32 refactor(CodeQuality): Improve Code Quality (2)
  pom.xml
  src/main/kotlin/com/expediagroup/sdk/core/config/Config.kt
  src/main/kotlin/com/expediagroup/sdk/core/config/ConfigurationDefinition.kt
  src/main/kotlin/com/expediagroup/sdk/core/config/provider/FileConfigurationProvider.kt
  src/main/kotlin/com/expediagroup/sdk/core/model/error/ErrorCause.kt
  src/main/kotlin/com/expediagroup/sdk/core/plugin/Hook.kt
  src/main/kotlin/com/expediagroup/sdk/core/plugin/authentication/AuthenticationHook.kt
  src/test/kotlin/com/expediagroup/sdk/core/commons/ClientFactory.kt
  src/test/kotlin/com/expediagroup/sdk/core/commons/MockEnginFactory.kt
  src/test/kotlin/com/expediagroup/sdk/core/config/ConfigTest.kt
  src/test/kotlin/com/expediagroup/sdk/core/config/provider/FileConfigurationProviderTest.kt
Labels: Refactor, WIP

#33 refactor(CodeQuality): Improve Code Quality (3)
  src/main/kotlin/com/expediagroup/sdk/core/config/Config.kt
  src/main/kotlin/com/expediagroup/sdk/core/config/ConfigurationDefinition.kt
  src/main/kotlin/com/expediagroup/sdk/core/config/provider/ConfigurationData.kt
  src/main/kotlin/com/expediagroup/sdk/core/config/provider/FileConfigurationProvider.kt
  src/main/kotlin/com/expediagroup/sdk/core/configuration/collector/ConfigurationCollector.kt
  src/main/kotlin/com/expediagroup/sdk/core/plugin/Plugin.kt
  src/main/kotlin/com/expediagroup/sdk/core/plugin/authentication/AuthenticationPlugin.kt
  src/test/kotlin/com/expediagroup/sdk/core/exception/ServiceExceptionTest.kt
  src/test/kotlin/com/expediagroup/sdk/core/plugin/authentication/AuthenticationPluginTest.kt
  src/test/kotlin/com/expediagroup/sdk/core/plugin/request/DefaultRequestPluginTest.kt
Labels: Refactor, Ready

#38 refactor(CodeQuality): Improve Code Quality (5)
  src/main/kotlin/com/expediagroup/sdk/core/client/openapi/OpenApiStub.kt
  src/main/kotlin/com/expediagroup/sdk/core/config/ConfigurationDefinition.kt
  src/main/kotlin/com/expediagroup/sdk/core/constant/Constant.kt
  src/main/kotlin/com/expediagroup/sdk/core/model/error/Error.kt
  src/main/kotlin/com/expediagroup/sdk/core/model/error/ErrorCause.kt
  src/test/kotlin/com/expediagroup/sdk/core/config/ConfigurationDefinitionTest.kt
Labels: Refactor, Ready

#39 feat(CodeQuality): Add Code Quality Rules
  .editorconfig
  detekt.yml
  pom.xml
Labels: Ready

#40 Update dependabot.yml
  .github/dependabot.yml
Labels: Ready

#41 fix(configurations): Fix Endpoint Write Logic
  src/main/kotlin/com/expediagroup/sdk/core/configuration/provider/FileSystemConfigurationProvider.kt
  src/test/kotlin/com/expediagroup/sdk/core/configuration/provider/FileSystemConfigurationProviderTest.kt
  src/test/resources/configurations-empty.properties
  src/test/resources/configurations-without-slash.properties
  src/test/resources/credentials-empty.properties
Labels: Ready
