Repository ExpediaGroup/expediagroup-java-sdk, pull requests merged in 2022-09, with the labels that each got.

#10 added support for configuration definitions
  src/main/kotlin/com/expediagroup/sdk/core/config/Configuration.kt
  src/main/kotlin/com/expediagroup/sdk/core/config/ConfigurationDefinition.kt
  src/main/kotlin/com/expediagroup/sdk/core/config/ConfigurationKey.kt
  src/test/kotlin/com/expediagroup/sdk/core/config/ConfigKeyTest.kt
  src/test/kotlin/com/expediagroup/sdk/core/config/ConfigTest.kt
  src/test/kotlin/com/expediagroup/sdk/core/config/ConfigurationDefinitionTest.kt
  src/test/resources/test_configuration.properties
Labels: Ready

#14 refactor(configurations)!: Rename BaseURL and AuthURL
  src/main/kotlin/com/expediagroup/sdk/core/config/EnvironmentConfigs.kt
  src/main/kotlin/com/expediagroup/sdk/core/config/EnvironmentConfigurationProvider.kt
  src/main/kotlin/com/expediagroup/sdk/core/constants/ClientConstants.kt
  src/main/kotlin/com/expediagroup/sdk/core/plugin/defaultRequests/DefaultRequestsPlugin.kt
  src/test/kotlin/com/expediagroup/sdk/core/commons/ClientFactory.kt
  src/test/kotlin/com/expediagroup/sdk/core/plugin/authentication/AuthenticationPluginTest.kt
  src/test/kotlin/com/expediagroup/sdk/core/plugin/defaultRequests/DefaultRequestsPluginTest.kt
Labels: Refactor, Ready

#15 feat(configurations): Support Configuration Providers
  src/main/kotlin/com/expediagroup/sdk/core/configuration/collecter/ConfigurationCollector.kt
  src/main/kotlin/com/expediagroup/sdk/core/configuration/collecter/ConfigurationProviderQueue.kt
  src/main/kotlin/com/expediagroup/sdk/core/configuration/provider/ConfigurationProvider.kt
  src/main/kotlin/com/expediagroup/sdk/core/configuration/provider/DefaultConfigurationProvider.kt
  src/main/kotlin/com/expediagroup/sdk/core/configuration/provider/FileSystemConfigurationProvider.kt
  src/main/kotlin/com/expediagroup/sdk/core/configuration/provider/RuntimeConfigurationProvider.kt
  src/test/kotlin/com/expediagroup/sdk/core/configuration/collecter/ConfigurationCollectorTest.kt
  src/test/kotlin/com/expediagroup/sdk/core/configuration/collecter/ConfigurationProviderQueueTest.kt
  src/test/kotlin/com/expediagroup/sdk/core/configuration/provider/DefaultConfigurationProviderTest.kt
  src/test/kotlin/com/expediagroup/sdk/core/configuration/provider/FileSystemConfigurationProviderTest.kt
  src/test/kotlin/com/expediagroup/sdk/core/configuration/provider/RuntimeConfigurationProviderTest.kt
  src/test/resources/configurations.properties
  src/test/resources/credentials.properties
Labels: Ready

#16 refactor(configurations): Drop the ClientConfiguration Class and Replace Java Tests with Kotlin
  src/main/kotlin/com/expediagroup/sdk/core/client/Client.kt
  src/main/kotlin/com/expediagroup/sdk/core/config/ClientConfiguration.kt
  src/main/kotlin/com/expediagroup/sdk/core/config/ClientCredentials.kt
  src/main/kotlin/com/expediagroup/sdk/core/config/Configuration.kt
  src/main/kotlin/com/expediagroup/sdk/core/config/Credentials.kt
  src/main/kotlin/com/expediagroup/sdk/core/config/EnvironmentConfigurationProvider.kt
  src/main/kotlin/com/expediagroup/sdk/core/plugin/authentication/AuthenticationConfigs.kt
  src/main/kotlin/com/expediagroup/sdk/core/plugin/authentication/AuthenticationPlugin.kt
  src/test/java/com/expediagroup/sdk/core/config/ConfigurationTest.java
  src/test/kotlin/com/expediagroup/sdk/core/commons/ClientFactory.kt
  src/test/kotlin/com/expediagroup/sdk/core/config/ConfigurationTest.kt
  src/test/kotlin/com/expediagroup/sdk/core/plugin/authentication/AuthenticationPluginTest.kt
Labels: Refactor, Ready

#17 feat(configurations): Add ClientConfiguration Class
  src/main/kotlin/com/expediagroup/sdk/core/client/Client.kt
  src/main/kotlin/com/expediagroup/sdk/core/client/openapi/OpenApiStub.kt
  src/main/kotlin/com/expediagroup/sdk/core/configuration/ClientConfiguration.kt
  src/test/kotlin/com/expediagroup/sdk/core/configuration/ClientConfigurationTest.kt
Labels: Ready

#18 feat(configurations): Accept and Use ClientConfiguration from our SDK Users
  src/main/kotlin/com/expediagroup/sdk/core/client/Client.kt
  src/main/kotlin/com/expediagroup/sdk/core/config/Credentials.kt
  src/main/kotlin/com/expediagroup/sdk/core/config/EnvironmentConfigs.kt
  src/main/kotlin/com/expediagroup/sdk/core/config/EnvironmentConfigurationProvider.kt
  src/main/kotlin/com/expediagroup/sdk/core/plugin/defaultRequests/DefaultRequestsConfigs.kt
  src/main/kotlin/com/expediagroup/sdk/core/plugin/defaultRequests/DefaultRequestsPlugin.kt
  src/test/kotlin/com/expediagroup/sdk/core/commons/ClientFactory.kt
  src/test/kotlin/com/expediagroup/sdk/core/commons/MockEnginFactory.kt
  src/test/kotlin/com/expediagroup/sdk/core/exceptions/ServiceExceptionTest.kt
  src/test/kotlin/com/expediagroup/sdk/core/plugin/authentication/AuthenticationPluginTest.kt
  src/test/kotlin/com/expediagroup/sdk/core/plugin/defaultRequests/DefaultRequestsPluginTest.kt
Labels: Ready

#19 refactor: Fix a typo: collecter -> collector
  src/main/kotlin/com/expediagroup/sdk/core/client/Client.kt
  src/main/kotlin/com/expediagroup/sdk/core/configuration/collector/ConfigurationCollector.kt
  src/main/kotlin/com/expediagroup/sdk/core/configuration/collector/ConfigurationProviderQueue.kt
  src/test/kotlin/com/expediagroup/sdk/core/configuration/collector/ConfigurationCollectorTest.kt
  src/test/kotlin/com/expediagroup/sdk/core/configuration/collector/ConfigurationProviderQueueTest.kt
Labels: Refactor, Ready

#20 refactor(configurations): Move Entities to Configuration Package
  src/main/kotlin/com/expediagroup/sdk/core/client/Client.kt
  src/main/kotlin/com/expediagroup/sdk/core/config/Config.kt
  src/main/kotlin/com/expediagroup/sdk/core/config/package-info.java
  src/main/kotlin/com/expediagroup/sdk/core/configuration/Credentials.kt
  src/main/kotlin/com/expediagroup/sdk/core/configuration/LoggingConfiguration.kt
  src/main/kotlin/com/expediagroup/sdk/core/configuration/NetworkConfiguration.kt
  src/main/kotlin/com/expediagroup/sdk/core/plugin/authentication/AuthenticationConfigs.kt
  src/main/kotlin/com/expediagroup/sdk/core/plugin/authentication/AuthenticationPlugin.kt
  src/test/kotlin/com/expediagroup/sdk/core/config/ConfigurationTest.kt
  src/test/kotlin/com/expediagroup/sdk/core/plugin/authentication/AuthenticationPluginTest.kt
Labels: Refactor, Ready

#23 refactor(test): Remove a Problematic Test
  src/test/kotlin/com/expediagroup/sdk/core/configuration/provider/FileSystemConfigurationProviderTest.kt
Labels: Refactor, Ready

#27 build: Adding new github build stage action
  .github/workflows/github-build-stage-action.yml
Labels: Approved

#26 refactor(model): Refactor Errors and Exceptions to a Model Package
  pom.xml
  src/main/kotlin/com/expediagroup/sdk/core/client/openapi/OpenApiStub.kt
  src/main/kotlin/com/expediagroup/sdk/core/config/Config.kt
  src/main/kotlin/com/expediagroup/sdk/core/config/ConfigurationDefinition.kt
  src/main/kotlin/com/expediagroup/sdk/core/config/provider/FileConfigurationProvider.kt
  src/main/kotlin/com/expediagroup/sdk/core/exception/error/Error.kt
  src/main/kotlin/com/expediagroup/sdk/core/exception/error/ErrorCause.kt
  src/main/kotlin/com/expediagroup/sdk/core/model/error/Error.kt
  src/main/kotlin/com/expediagroup/sdk/core/model/error/ErrorCause.kt
  src/main/kotlin/com/expediagroup/sdk/core/model/exception/BaseException.kt
  src/main/kotlin/com/expediagroup/sdk/core/model/exception/ClientException.kt
  src/main/kotlin/com/expediagroup/sdk/core/model/exception/ConfigurationException.kt
  src/main/kotlin/com/expediagroup/sdk/core/model/exception/ServiceException.kt
  src/main/kotlin/com/expediagroup/sdk/core/plugin/authentication/AuthenticationPlugin.kt
  src/test/kotlin/com/expediagroup/sdk/core/config/ConfigTest.kt
  src/test/kotlin/com/expediagroup/sdk/core/config/ConfigurationDefinitionTest.kt
  src/test/kotlin/com/expediagroup/sdk/core/config/provider/FileConfigurationProviderTest.kt
  src/test/kotlin/com/expediagroup/sdk/core/configuration/provider/FileSystemConfigurationProviderTest.kt
  src/test/kotlin/com/expediagroup/sdk/core/exception/ServiceExceptionTest.kt
  src/test/kotlin/com/expediagroup/sdk/core/plugin/authentication/AuthenticationPluginTest.kt
Labels: Refactor, Ready

#31 refactor(CodeQuality): Improve Code Quality (1)
  src/main/kotlin/com/expediagroup/sdk/core/client/Client.kt
  src/main/kotlin/com/expediagroup/sdk/core/client/openapi/OpenApiStub.kt
  src/main/kotlin/com/expediagroup/sdk/core/config/ConfigurationDefinition.kt
  src/main/kotlin/com/expediagroup/sdk/core/config/ConfigurationKey.kt
  src/main/kotlin/com/expediagroup/sdk/core/config/provider/ConfigurationData.kt
  src/main/kotlin/com/expediagroup/sdk/core/config/provider/ConfigurationProvider.kt
  src/main/kotlin/com/expediagroup/sdk/core/config/provider/FileConfigurationProvider.kt
  src/main/kotlin/com/expediagroup/sdk/core/configuration/ClientConfiguration.kt
  src/main/kotlin/com/expediagroup/sdk/core/configuration/Credentials.kt
  src/main/kotlin/com/expediagroup/sdk/core/configuration/provider/ConfigurationProvider.kt
  src/main/kotlin/com/expediagroup/sdk/core/configuration/provider/FileSystemConfigurationProvider.kt
  src/main/kotlin/com/expediagroup/sdk/core/model/error/ErrorCause.kt
Labels: Refactor, Ready
