Repository ExpediaGroup/expediagroup-java-sdk, pull requests merged in 2023-01, with the labels that each got.

#86 Rename packages
  pom.xml
  src/main/kotlin/com/expediagroup/sdk/core/client/Client.kt
  src/main/kotlin/com/expediagroup/sdk/core/plugin/authentication/AuthenticationConfiguration.kt
  src/main/kotlin/com/expediagroup/sdk/core/plugin/authentication/AuthenticationPlugin.kt
  src/main/kotlin/com/expediagroup/sdk/core/plugin/authentication/strategy/AuthenticationStrategy.kt
  src/main/kotlin/com/expediagroup/sdk/core/plugin/authentication/strategy/bearer/BearerStrategy.kt
  src/main/kotlin/com/expediagroup/sdk/core/plugin/authentication/strategy/bearer/BearerTokensInfo.kt
  src/main/kotlin/com/expediagroup/sdk/core/plugin/authentication/strategy/bearer/TokenResponse.kt
  src/main/kotlin/com/expediagroup/sdk/core/plugin/authentication/strategy/signature/SignatureCalculator.kt
  src/main/kotlin/com/expediagroup/sdk/core/plugin/authentication/strategy/signature/SignatureStrategy.kt
  src/test/kotlin/com/expediagroup/sdk/core/plugin/authentication/AuthenticationPluginTest.kt
  src/test/kotlin/com/expediagroup/sdk/core/plugin/authentication/strategy/signature/SignatureCalculatorTest.kt
Labels: Approved

#88 chore(release): Upgrade Core Version
  pom.xml
Labels: Ready

#85 Increase logging information
  src/main/kotlin/com/expediagroup/sdk/core/configuration/collector/ConfigurationCollector.kt
  src/main/kotlin/com/expediagroup/sdk/core/configuration/provider/ConfigurationProvider.kt
  src/main/kotlin/com/expediagroup/sdk/core/configuration/provider/DefaultConfigurationProvider.kt
  src/main/kotlin/com/expediagroup/sdk/core/configuration/provider/FileSystemConfigurationProvider.kt
  src/main/kotlin/com/expediagroup/sdk/core/configuration/provider/RuntimeConfigurationProvider.kt
  src/main/kotlin/com/expediagroup/sdk/core/constant/ConfigurationName.kt
  src/main/kotlin/com/expediagroup/sdk/core/constant/Constant.kt
  src/main/kotlin/com/expediagroup/sdk/core/constant/LoggingMessage.kt
  src/main/kotlin/com/expediagroup/sdk/core/constant/provider/LoggingMessageProvider.kt
Labels: Changes Requested

#93 chore(build): Upgrade to Kotlin 1.8
  pom.xml
Labels: Ready

#102 Update core version
  pom.xml
Labels: Approved

#106 chore(version): Upgrade Version
  pom.xml
Labels: Approved

#108 feat(logging): Mask Tokens in Logs
  src/main/kotlin/com/expediagroup/sdk/core/constant/Authentication.kt
  src/main/kotlin/com/expediagroup/sdk/core/constant/LogMaskingRegex.kt
  src/main/kotlin/com/expediagroup/sdk/core/constant/LoggingMessage.kt
  src/main/kotlin/com/expediagroup/sdk/core/plugin/logging/LogMasker.kt
  src/main/kotlin/com/expediagroup/sdk/core/plugin/logging/OpenWorldLogger.kt
  src/test/kotlin/com/expediagroup/sdk/core/plugin/logging/LogMaskerTest.kt
  src/test/kotlin/com/expediagroup/sdk/core/plugin/logging/OpenWorldLoggerTest.kt
Labels: Ready

#104 Fix singleton issues
  src/main/kotlin/com/expediagroup/sdk/core/client/Client.kt
  src/main/kotlin/com/expediagroup/sdk/core/constant/Authentication.kt
  src/main/kotlin/com/expediagroup/sdk/core/constant/ExceptionMessage.kt
  src/main/kotlin/com/expediagroup/sdk/core/plugin/Hook.kt
  src/main/kotlin/com/expediagroup/sdk/core/plugin/Plugin.kt
  src/main/kotlin/com/expediagroup/sdk/core/plugin/authentication/AuthenticationHookFactory.kt
  src/main/kotlin/com/expediagroup/sdk/core/plugin/authentication/AuthenticationPlugin.kt
  src/main/kotlin/com/expediagroup/sdk/core/plugin/authentication/strategy/AuthenticationStrategy.kt
  src/main/kotlin/com/expediagroup/sdk/core/plugin/authentication/strategy/bearer/BearerStrategy.kt
  src/main/kotlin/com/expediagroup/sdk/core/plugin/authentication/strategy/signature/SignatureStrategy.kt
  src/main/kotlin/com/expediagroup/sdk/core/plugin/encoding/EncodingPlugin.kt
  src/main/kotlin/com/expediagroup/sdk/core/plugin/logging/LoggingPlugin.kt
  src/main/kotlin/com/expediagroup/sdk/core/plugin/request/DefaultRequestPlugin.kt
  src/main/kotlin/com/expediagroup/sdk/core/plugin/serialization/SerializationPlugin.kt
  src/test/kotlin/com/expediagroup/sdk/core/commons/ClientFactory.kt
  src/test/kotlin/com/expediagroup/sdk/core/plugin/authentication/AuthenticationPluginTest.kt
  src/test/kotlin/com/expediagroup/sdk/core/plugin/encoding/EncodingPluginTest.kt
Labels: Ready

#110 chore(build): Publish Core 0.8.1
  pom.xml
Labels: Ready

#107 fix(logging): Remove Redundant Configuration Logs
  src/main/kotlin/com/expediagroup/sdk/core/configuration/collector/ConfigurationCollector.kt
  src/main/kotlin/com/expediagroup/sdk/core/configuration/collector/ConfigurationProviderQueue.kt
  src/test/kotlin/com/expediagroup/sdk/core/configuration/collector/ConfigurationProviderQueueTest.kt
Labels: Ready
