Repository ExpediaGroup/expediagroup-java-sdk, pull requests merged in 2024-08, with the labels that each got.

#637 chore: add test run interface github action
  .github/workflows/generator-generate.yaml
  .github/workflows/generator-test-sdk.yaml
  .github/workflows/run-tests.yaml
Labels: Approved

#653 feat: SDK-1405 support self-serve spec transforming
  .github/workflows/selfserve-generate.yaml
  .github/workflows/selfserve-transform-specs.yaml
Labels: Ready for Review

#668 feat: SDK-1407 support self-serve sdk release
  .github/workflows/selfserve-release.yaml
  generator/openapi/src/main/resources/templates/expediagroup-sdk/pom.mustache
Labels: Ready for Review

#672 feat: SDK-1407 support self-serve full workflow (transform, generate, publish sources, and release to Maven)
  .github/workflows/selfserve-full-workflow.yaml
  .github/workflows/selfserve-generate.yaml
  .github/workflows/selfserve-publish-sources.yaml
  .github/workflows/selfserve-upload-specs.yaml
  generator/openapi/src/main/resources/templates/expediagroup-sdk/pom.mustache
Labels: Ready for Review

#673 chore: add a note on how to release a snapshot SDK on the old actions
  .github/workflows/generator-main.yaml
Labels: Ready for Review

#688 chore: configure renovate to update dependencies in mustache files
  renovate.json
Labels: Ready for Review

#681 feat: post-process generated files
  .github/workflows/generator-generate.yaml
  .github/workflows/selfserve-generate.yaml
  generator/openapi/pom.xml
  generator/openapi/src/main/kotlin/com/expediagroup/sdk/generators/openapi/OpenApiSdkGenerator.kt
  generator/openapi/src/main/resources/post-processor/eslint.config.js
  generator/openapi/src/main/resources/post-processor/package-lock.json
  generator/openapi/src/main/resources/post-processor/package.json
  generator/openapi/src/main/resources/post-processor/processor.ts
  generator/openapi/src/main/resources/post-processor/processors/trader-details-inner.ts
  generator/openapi/src/main/resources/post-processor/rules/trader-details-inner/add-default-value.yaml
  generator/openapi/src/main/resources/post-processor/rules/trader-details-inner/add-imports.yaml
  generator/openapi/src/main/resources/post-processor/rules/trader-details-inner/add-json-setter.yaml
  generator/openapi/src/main/resources/post-processor/tsconfig.json
Labels: Don't Review

#702 feat: support combining generator templates
  .github/workflows/generator-test-sdk.yaml
  .github/workflows/selfserve-checkout-and-upload.yaml
  .github/workflows/selfserve-combine-templates.yaml
  .github/workflows/selfserve-full-workflow.yaml
  .github/workflows/selfserve-generate-sdk.yaml
  .github/workflows/selfserve-publish-sources.yaml
  .github/workflows/selfserve-release-sdk.yaml
  .github/workflows/selfserve-upload-specs.yaml
Labels: Ready for Review
